# configs/config_vars.yaml
worker-threads: 4
worker-fs-threads: 2
logger-level: debug

is_testing: false

server-port: 8080

dbconnection: 'postgresql://pg-lecture_user:password@localhost:5432/pg-lecture_db-1'
